services:
  app:
    build: .
    container_name: servicio-reservas
    ports:
      - "3002:3002"
    environment:
      # Sobrescribir variables del .env para Docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: usuario
      DB_PASSWORD: usuario123
      DB_NAME: db_smartride_reservas
      RABBITMQ_URL: amqp://guest:guest@rabbitmq
      RABBITMQ_EXCHANGE: smart_ride_exchange
      JWT_SECRET: 3583fbebc94b3a65b11d63e791f49e7de5e4b8bde1bb8548e707f1a78f321c6118f3aa0edf7d1c1429bb199979241ad30a8447acc27c085a89148647b254f402 
      PORT: 3002
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - smartride-network
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: rideservice-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: usuario123
      MYSQL_DATABASE: db_smartride_reservas
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smartride-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "usuario", "-usuario123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rideservice-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - smartride-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  smartride-network:
    driver: bridge